### ISSUE TITLE
Please join in some nostalgic Codename Eagle actions!

### ISSUE THREAD

**Issue by codenameeaglebest** [rexxars/openttd-no-maglev#1]
Hello Rexxars!
I wanted to inform you that we have spun up a new dedicated server for codename eagle! It will be online for 2021 at least.
So far we have about 5 or so regular players. One Australian fellow, cobox, said he knew you back in the day.
Anyway, I was wondering if you could find it in your heart to either link to our server's website, and/or add
our server to your server status page at codenameeagle.net. 

Our server IP is: 89.38.98.12
Our website is: https://codenameeaglemultiplayer.com

Lastly, we would be honored if you would join us for a game at some point. It's still early days,
but we've had a couple good games already. Usually the server is more populated on the weekends.

This weekend, saturday in particular, we are planning a big-ish game (3v3 or more!). 

Whether or not you can join the game, it would be great to hear from you - we have a chat link
on our website too. 

Lastly, thank you very much for maintaining codenameeagle.net for so long. You are a hero to codename eagle fans everywhere!

Cheers!

**Comment by rexxars** [comment]
👋  Thanks! Joined you on IRC :)
